name: UrbanSound • SageMaker OIDC MLOps

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      force_retrain:
        description: "Force SageMaker training"
        default: "false"
      endpoint_env:
        description: "Endpoint environment"
        default: "staging"
        type: choice
        options: [staging, production]
      train_instance_type:
        description: "SageMaker Training InstanceType"
        default: "ml.m5.large"
      serve_instance_type:
        description: "Endpoint InstanceType"
        default: "ml.g4dn.xlarge"

env:
  AWS_REGION: us-east-2
  AWS_ACCOUNT_ID: "564230509626"
  S3_BUCKET: urbansound-mlops-56423506
  TRAIN_ECR_REPOSITORY: urbansound-train
  INFER_ECR_REPOSITORY: urbansound-infer
  SAGEMAKER_EXECUTION_ROLE_ARN: arn:aws:iam::564230509626:role/urbansound-sagemaker-execution
  OIDC_ROLE_ARN: arn:aws:iam::564230509626:role/urbansound-github-actions-v2
  ENDPOINT_NAME_BASE: urbansound-audio
  PYTHON_VERSION: "3.11"

permissions:
  id-token: write
  contents: read

concurrency:
  group: mlops-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-and-push-images:
    name: Build & Push (ECR)
    runs-on: ubuntu-latest
    outputs:
      train-image-uri: ${{ steps.out-train.outputs.TRAIN_IMAGE_URI }}
      infer-image-uri: ${{ steps.out-infer.outputs.INFER_IMAGE_URI }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-skip-session-tagging: true
          
      - name: ECR Login
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2
        
      - name: Build & Push TRAIN image
        id: build-train
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/training/Dockerfile
          push: true
          provenance: false
          tags: |
            ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.TRAIN_ECR_REPOSITORY }}:${{ github.sha }}
            ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.TRAIN_ECR_REPOSITORY }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            GIT_SHA=${{ github.sha }}
            
      - name: Build & Push INFER image
        id: build-infer
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/inference/Dockerfile
          push: true
          provenance: false
          tags: |
            ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.INFER_ECR_REPOSITORY }}:${{ github.sha }}
            ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.INFER_ECR_REPOSITORY }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            GIT_SHA=${{ github.sha }}
            
      - name: Output Train URI
        id: out-train
        run: |
          echo "TRAIN_IMAGE_URI=${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.TRAIN_ECR_REPOSITORY }}:${{ github.sha }}" >> $GITHUB_OUTPUT
          
      - name: Output Infer URI
        id: out-infer
        run: |
          echo "INFER_IMAGE_URI=${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.INFER_ECR_REPOSITORY }}:${{ github.sha }}" >> $GITHUB_OUTPUT

  sagemaker-train-and-deploy:
    name: Train & Deploy (SageMaker)
    needs: build-and-push-images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      - name: Install deps for control script
        run: pip install boto3 botocore pyyaml
        
      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-skip-session-tagging: true
          
      - name: Train + (Re)Deploy Endpoint
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
          S3_BUCKET: ${{ env.S3_BUCKET }}
          SAGEMAKER_EXECUTION_ROLE_ARN: ${{ env.SAGEMAKER_EXECUTION_ROLE_ARN }}
          TRAIN_IMAGE_URI: ${{ needs.build-and-push-images.outputs.train-image-uri }}
          INFER_IMAGE_URI: ${{ needs.build-and-push-images.outputs.infer-image-uri }}
          ENDPOINT_NAME_BASE: ${{ env.ENDPOINT_NAME_BASE }}
          FORCE_RETRAIN: ${{ inputs.force_retrain || 'false' }}
          INSTANCE_TYPE: ${{ inputs.train_instance_type }}
          SERVE_INSTANCE_TYPE: ${{ inputs.serve_instance_type }}
          ENDPOINT_ENV: ${{ inputs.endpoint_env }}
          GIT_SHA: ${{ github.sha }}
        run: python scripts/sm_train_and_deploy.py

