name: "UrbanSound • SageMaker OIDC MLOps"
permissions:
  id-token: write
  contents: read
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      force_retrain:
        description: "Force SageMaker training"
        default: "false"
      endpoint_env:
        description: "Endpoint environment"
        type: choice
        options: [ staging, production ]
        default: staging
      train_instance_type:
        description: "SageMaker Training InstanceType"
        default: "ml.m5.large"
      serve_instance_type:
        description: "SageMaker Inference InstanceType"
        default: "ml.g4dn.xlarge"
env:
  AWS_REGION: us-east-2
  AWS_ACCOUNT_ID: "564230509626"
  S3_BUCKET: urbansound-mlops-56423506
  TRAIN_ECR_REPOSITORY: urbansound-train
  INFER_ECR_REPOSITORY: urbansound-infer
  SAGEMAKER_EXECUTION_ROLE_ARN: arn:aws:iam::564230509626:role/urbansound-sagemaker-execution
  OIDC_ROLE_ARN: arn:aws:iam::564230509626:role/urbansound-github-actions-v2
  ENDPOINT_NAME_BASE: urbansound-audio
  PYTHON_VERSION: "3.11"
concurrency:
  group: mlops-${{ github.ref }}
  cancel-in-progress: false
jobs:
  build-and-push-images:
    name: Build & Push (ECR)
    runs-on: ubuntu-latest
    outputs:
      TRAIN_IMAGE_TAG:     ${{ steps.out-train.outputs.TRAIN_IMAGE_TAG }}
      INFER_IMAGE_TAG:     ${{ steps.out-infer.outputs.INFER_IMAGE_TAG }}
      TRAIN_IMAGE_DIGEST:  ${{ steps.digest-train.outputs.TRAIN_IMAGE_DIGEST }}
      INFER_IMAGE_DIGEST:  ${{ steps.digest-infer.outputs.INFER_IMAGE_DIGEST }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-skip-session-tagging: true
      - name: ECR Login
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build & Push TRAIN image
        id: build-train
        uses: docker/build-push-action@v6
        with:
          context: docker/training
          file: docker/training/Dockerfile
          push: true
          provenance: false
          no-cache: true
          tags: |
            ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.TRAIN_ECR_REPOSITORY }}:${{ github.sha }}
            ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.TRAIN_ECR_REPOSITORY }}:latest
          build-args: |
            GIT_SHA=${{ github.sha }}
      - name: Build & Push INFER image
        id: build-infer
        uses: docker/build-push-action@v6
        with:
          context: docker/inference
          file: docker/inference/Dockerfile
          push: true
          provenance: false
          no-cache: true
          tags: |
            ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.INFER_ECR_REPOSITORY }}:${{ github.sha }}
            ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.INFER_ECR_REPOSITORY }}:latest
          build-args: |
            GIT_SHA=${{ github.sha }}
      - name: Output TRAIN tag URI
        id: out-train
        shell: bash
        run: |
          set -euo pipefail
          echo "TRAIN_IMAGE_TAG=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${TRAIN_ECR_REPOSITORY}:${GITHUB_SHA}" >> "$GITHUB_OUTPUT"
      - name: Output INFER tag URI
        id: out-infer
        shell: bash
        run: |
          set -euo pipefail
          echo "INFER_IMAGE_TAG=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${INFER_ECR_REPOSITORY}:${GITHUB_SHA}" >> "$GITHUB_OUTPUT"
      - name: Resolve TRAIN image digest
        id: digest-train
        shell: bash
        run: |
          set -euo pipefail
          DIGEST=$(aws ecr describe-images \
            --repository-name "${TRAIN_ECR_REPOSITORY}" \
            --image-ids imageTag="${GITHUB_SHA}" \
            --query 'imageDetails[0].imageDigest' --output text)
          FULL="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${TRAIN_ECR_REPOSITORY}@${DIGEST}"
          printf "TRAIN_IMAGE_DIGEST=%s\n" "$FULL" >> "$GITHUB_OUTPUT"
      - name: Resolve INFER image digest
        id: digest-infer
        shell: bash
        run: |
          set -euo pipefail
          DIGEST=$(aws ecr describe-images \
            --repository-name "${INFER_ECR_REPOSITORY}" \
            --image-ids imageTag="${GITHUB_SHA}" \
            --query 'imageDetails[0].imageDigest' --output text)
          FULL="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${INFER_ECR_REPOSITORY}@${DIGEST}"
          printf "INFER_IMAGE_DIGEST=%s\n" "$FULL" >> "$GITHUB_OUTPUT"
      - name: "Guardrail: training and inference are different images"
        shell: bash
        run: |
          set -euo pipefail
          if [ "${{ steps.digest-train.outputs.TRAIN_IMAGE_DIGEST }}" = "${{ steps.digest-infer.outputs.INFER_IMAGE_DIGEST }}" ]; then
            echo "Train and Infer images share the same digest. Aborting."
            exit 1
          fi
  sagemaker-train-and-deploy:
    name: Train & Deploy (SageMaker)
    needs: build-and-push-images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install deps
        run: |
          pip install boto3 botocore pyyaml
          pip install comet_ml
      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-skip-session-tagging: true
      - name: Train + (Re)Deploy Endpoint
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
          S3_BUCKET: ${{ env.S3_BUCKET }}
          SAGEMAKER_EXECUTION_ROLE_ARN: ${{ env.SAGEMAKER_EXECUTION_ROLE_ARN }}
          ENDPOINT_NAME_BASE: ${{ env.ENDPOINT_NAME_BASE }}
          # *** PIN TO DIGESTS ***
          TRAIN_IMAGE_URI: ${{ needs.build-and-push-images.outputs.TRAIN_IMAGE_DIGEST }}
          INFER_IMAGE_URI: ${{ needs.build-and-push-images.outputs.INFER_IMAGE_DIGEST }}
          FORCE_RETRAIN: ${{ github.event.inputs.force_retrain || 'false' }}
          INSTANCE_TYPE: ${{ github.event.inputs.train_instance_type || 'ml.m5.large' }}
          SERVE_INSTANCE_TYPE: ${{ github.event.inputs.serve_instance_type || 'ml.g4dn.xlarge' }}
          ENDPOINT_ENV: ${{ github.event.inputs.endpoint_env || 'staging' }}
          GIT_SHA: ${{ github.sha }}
        run: |
          python scripts/sm_train_and_deploy.py \
            --region "$AWS_REGION" \
            --bucket "$S3_BUCKET" \
            --execution-role "$SAGEMAKER_EXECUTION_ROLE_ARN" \
            --train-image-uri "$TRAIN_IMAGE_URI" \
            --infer-image-uri "$INFER_IMAGE_URI" \
            --endpoint-base "$ENDPOINT_NAME_BASE" \
            --force-retrain "$FORCE_RETRAIN" \
            --train-instance "$INSTANCE_TYPE" \
            --serve-instance "$SERVE_INSTANCE_TYPE" \
            --env "$ENDPOINT_ENV" \
            --git-sha "$GIT_SHA"
